on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TEAMSAPP_CLI_VERSION: "3.0.0"
      BOT_AZURE_APP_SERVICE_RESOURCE_ID: ${{vars.BOT_AZURE_APP_SERVICE_RESOURCE_ID}}
      BOT_ID: ${{vars.BOT_ID}}
      TEAMS_APP_ID: ${{vars.TEAMS_APP_ID}}
      APP_NAME_SUFFIX: ${{vars.APP_NAME_SUFFIX}}
      # Add extra environment variables here so that teamsapp cli can use them.

    steps:
      - name: "Checkout Github Action"
        uses: actions/checkout@master

      - name: Setup Node 20.x
        uses: actions/setup-node@v1
        with:
          node-version: "20.8.1"


      - name: install cli
        run: |
          npm install -g @microsoft/teamsapp-cli@${{env.TEAMSAPP_CLI_VERSION}}
          npm install -g node-machine-id

      - name: "Print machine ID"
        run: |
          node -e "const { machineIdSync } = require('node-machine-id'); console.log(machineIdSync());"